version: '3.3'

volumes:
  synapse-data:

services:
  #synapse:
  #  build: docker/synapse
  #  container_name: synapse
  #  #network_mode: service:wireguard
  #  volumes:
  #    - synapse-data:/data
  #  ports:
  #    - 8008:8008

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      target: develop 
    container_name: client
    ports:
      - 3000:3000
      - 3010:3010
    volumes:
      - ./src:/app/src
  
