version: '3.3'

services:
  database:
    build: docker/database
    container_name: database
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: server 
    ports:
      - 3030:3030
    volumes:
      - ./src:/chat-client/src

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    depends_on: [ server ]
    container_name: client
    ports:
      - 3000:3000
      - 3010:3010
    volumes:
      - ./src:/chat-client/src
  
